# Generated by Django 4.1.4 on 2022-12-21 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('address_detail', models.TextField(verbose_name='address detail')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('capacity', models.SmallIntegerField(default=1)),
                ('rooms', models.SmallIntegerField(default=0)),
                ('single_bed', models.SmallIntegerField(default=0)),
                ('double_bed', models.SmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResidenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residence_features', to='residences.residence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='residence',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, related_name='residence_category', to='residences.residencecategory'),
        ),
        migrations.AddField(
            model_name='residence',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residence_city', to='locations.city'),
        ),
    ]
