# Generated by Django 4.1.4 on 2022-12-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
