# Generated by Django 4.1.4 on 2022-12-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0003_alter_residence_city_residencerule_residencerate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencerule',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
