# Generated by Django 4.1.4 on 2022-12-25 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('residences', '0004_alter_residencerule_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenceSpecialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='price_currency_%(class)s', to='currencies.currency')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_residence_price', to='residences.residence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResidenceDailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('day', models.PositiveSmallIntegerField(choices=[(5, 'saturday'), (6, 'sunday'), (0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday')], default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='price_currency_%(class)s', to='currencies.currency')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_residence_price', to='residences.residence')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
