# Generated by Django 4.1.4 on 2022-12-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0006_residencegallery_residencegalleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residencegallery',
            old_name='hotel',
            new_name='residence',
        ),
    ]
