# Generated by Django 4.1.4 on 2022-12-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0008_residencepassengerreservation_residencereservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencepassengerreservation',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
