# Generated by Django 4.1.4 on 2022-12-20 10:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abstracts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('abstractplace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abstracts.abstractplace')),
                ('star', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            bases=('abstracts.abstractplace',),
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('floor', models.SmallIntegerField()),
                ('pluck', models.PositiveSmallIntegerField()),
                ('extra_bed', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=True)),
                ('reserve', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoomFeature',
            fields=[
                ('abstractfeature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abstracts.abstractfeature')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_features', to='hotels.hotelroom')),
            ],
            bases=('abstracts.abstractfeature',),
        ),
        migrations.CreateModel(
            name='HotelRoomCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms_count', to='hotels.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_count', to='hotels.hotelroom')),
            ],
        ),
        migrations.CreateModel(
            name='HotelFeature',
            fields=[
                ('abstractfeature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abstracts.abstractfeature')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_features', to='hotels.hotel')),
            ],
            bases=('abstracts.abstractfeature',),
        ),
    ]
