# Generated by Django 4.1.4 on 2022-12-30 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomPassengerReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=32)),
                ('national_id', models.PositiveIntegerField()),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, ' male'), (2, 'female')], default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelRoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_room_reservation_passenger', to='hotels.hotelroompassengerreservation')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_room_reservations', to='hotels.hotelroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
