# Generated by Django 4.1.4 on 2022-12-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldailyprice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='price_currency_%(class)s', to='currencies.currency'),
        ),
        migrations.AlterField(
            model_name='hotelspecialprice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='price_currency_%(class)s', to='currencies.currency'),
        ),
    ]
