# Generated by Django 4.1.4 on 2022-12-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelroomfeature',
            old_name='Room',
            new_name='room',
        ),
    ]
