# Generated by Django 4.1.4 on 2022-12-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hoteldailyprice_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldailyprice',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(5, 'saturday'), (6, 'sunday'), (0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday')], default=0),
        ),
    ]
