# Generated by Django 4.1.4 on 2022-12-30 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotelroompassengerreservation_hotelroomreservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelroomreservation',
            old_name='residence',
            new_name='room',
        ),
    ]
