# Generated by Django 4.1.4 on 2022-12-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('hotels', '0002_hotellocations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelLocations',
            new_name='HotelLocation',
        ),
    ]
