# Generated by Django 4.1.4 on 2022-12-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_hotel_city_hotelrule_hotelrate_hotelcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrule',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
