# Generated by Django 4.1.4 on 2022-12-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightticket',
            name='flight_class',
            field=models.PositiveSmallIntegerField(choices=[(1, 'economy'), (2, 'business'), (3, 'first')]),
        ),
    ]
