# Generated by Django 4.1.4 on 2022-12-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightticket',
            name='price',
            field=models.CharField(max_length=15),
        ),
    ]
