# Generated by Django 4.1.4 on 2022-12-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flightreservation_flightpassenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightpassenger',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='flightpassenger',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='flightreservation',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='flightreservation',
            name='modified_time',
        ),
    ]
