# Generated by Django 4.1.4 on 2022-12-30 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flightpassengerreservation_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightreservation',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_reservation_passenger', to='flights.flightpassengerreservation'),
        ),
    ]
