# Generated by Django 4.1.4 on 2022-12-30 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0003_alter_flightreservation_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
