# Generated by Django 4.1.4 on 2022-12-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_flightpassenger_is_valid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlightPassenger',
            new_name='FlightPassengerReservation',
        ),
    ]
