# Generated by Django 4.1.4 on 2022-12-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'province'), name='unique_city_province'),
        ),
        migrations.AddConstraint(
            model_name='province',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='unique_province_country'),
        ),
    ]
